### ISSUE TITLE
Keyboard shortcuts broken globally

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/next#21] opened 2021-12-16 03:53 UTC
**Describe the bug**
Keyboard shortcuts do not work at all globally. No one has been able to confirm that they do work after someone noticed that they weren't working.

**Desktop (please complete the following information):**
 - OS: macOS, IOS, more
 - Browser: mobile Safari, Chrome, etc.

**Additional context**
This was noticed on 11/14 at 10 PM. Might be related to #16? Could have also broken during the update on 12/12, although I think I remember them working right after the update.

**Comment by Veirt** [comment] 2021-12-16 06:56
I can confirm the keyboard shortcut has already broken even BEFORE my pull request merged, since I use keyboard shortcuts a lot.

**Comment by CameronCT** [comment] 2021-12-19 03:23
Will be fixed in new update.

**Closed by CameronCT** 2021-12-19 03:23 UTC
Labels: bug
